from faker import Faker
from faker.providers import BaseProvider
fake = Faker()


class Provider(BaseProvider):
    skills = [
        "IE JEE",
        "décisionnel",
        "IE PHP/JEE",
        "MVS Cobol",
        ".Net",
        "Mainframe",
        "Java J2EE",
        "Java J2EE / JS ",
        " MOA / MOE",
        "HOST",
        "JAVA",
        "mainframe COBOL",
        "CP AMOA",
        "IE Mainframe (Cobol IDMS)",
        "BO",
        "Java débutant",
        "IE Java/J2EE 10 ans d'XP",
        "Mainframe (COBOL,IDMS, Pacbase, ...)",
        "CDP : PHP, .Net",
        "MOA / BI",
        "Java JEE - CDP",
        " Mainframe (COBOL, IDMS)",
        "IE VB/Excel/Access, test",
        "Java EE",
        "Talend",
        "PHP",
        "AMOA",
        " IE Java/J2EE",
        "Dev Java Web",
        "PL1, Test",
        "J2E",
        "junior JAVA J2EE",
        "Pilotage, analyse",
        "mvs pacbase cobol",
        "Agile coach, Scrum Master, Product-Owner",
        "MOA / Décisionnel - BO",
        "JAVA/ PHP",
        "JAVA J2EE R",
        " Développement Java",
        "CDP Java EE et mobilité",
        "dév Java EE",
        "Java EE et Talend",
        "Décisionnel BO, BIRT",
        "pmo/cp",
        "Technicien syst/réseaux",
        "Analyse et développement Mainframe",
        "CP - SCRUM MASTER",
        "chef de projet",
        "CDP .Net",
        "PACBASE",
        "AP Mainframe",
        "Analyse Cobol Pacbase",
        "BPL",
        "IED JAVA J2EE",
        "CP",
        "BPL - Test",
        "IED C/C++/Java",
        "ISPL PMO",
        "CP technique",
        "Support fonctionnel",
        "CP technique - Scrum Master",
        "JAVA JEE Junior",
        "HTML5, CSS3",
        "IOS",
        "FRONT END",
        "MVS, PACBASE",
        "CP JAVA J2EE",
        "COBOL/.Net",
        "SAP AMOA",
        "Expert JAVA/JEE LIFERAY",
        "IED JAVA/JEE",
        "Chef de projet Infra",
        "BPL - support technique et fonctionnel",
        "CP Infra",
        "Pépinière PACBASE",
        "IE Java-J2EE",
        "IE Java",
        "dot net",
        "IED/EXPERT JAVA JEE",
        "PMO Qualité Conception Décisionnel",
        "BPL - support",
        "IE C#, .Net, Java",
        "IED JAVA"
        "Développeur Pacbase/Cobol",
        "IED Mobile",
        "lead tech Java EE",
        "Fonctionnelle Test",
        "Java/J2EE expert",
        "DEV Android",
        "Technicien IT Infotel",
        "IED Avant Vente",
        "Java - intégration",
        "DEV WEB (HTML, CSS, PHP) C# .NET",
        "IED JAVA/JEE ANDROID (ex stagiaire)",
        "IED Infra/projet (ex stagiaire)",
        "IED ElasticStack/.Net C# (ex stagiaire)",
        "Testeur",
        "IED junior JAVA/JEE PHP",
        "Support technique & fonctionnel",
        "Access Management / IBM",
        "Support",
        "IED Junior C#/Angular/PHP (ex-alternant)"
        "IED WEB (PHP/JAVASCRIPT) /JAVAJEE/.NET (C#) - (ex-stagiaire)",
        "Ingénieur décisionnel (ex-stagiaire)",
        "IED (ex-stagiaire) ANDROID JAVA",
        "IED JUNIOR JAVA PLM",
        "IED BI (ex-stagiaire)",
        "DigDash, Pentaho, PowerBI, PHP, Qlikview (ex-stagiaire)",
        "Scala, Spark, Hadoop, MongoDB, C#, Java (ex-stagiaire)",
        "JEE",
        "Cobol Java (ex-stagiaire)",
        "PMO",
        "AVV, CP, Infrastructure",
        ".net, Front end,angular , java - 2-3 ans d'exp"
        "Pépinière Digitale",
        "Stagiaire (IED) Session JAVA"
        "stagiaire Session JAVA",
        "Ingénieur Technico Fonctionnel SAP",
        "Ingénieur Support Fonctionnel (ex-sous-traitant SVI)",
        "Gestion de projet MOE - AMOA",
        "MOA/Chef de Projet/ Dév. Java",
        "intégrateur/ développeur JEE",
        "CP/Scrum Master",
        "BPL (ex-soustraitant)",
        "Analyste Mainframe",
        "Consultant Fonctionnel (ex-soustraitant ATR)",
        "Consultante Fonctionnelle",
        "Consultant support SAP BI",
        ".NET(+) , JS",
        "Consultante Fonctionnelle JD",
        "Ingénieur JD (stage Analyste Fonctionnel SAP)",
        "Infra",
        "php JAVA",
        "Dev Java/JEE - Mobile Android/iOs",
        "CP Infra / ITPL /  Process ITIL",
        "MOA décisionnel",
        "Fonctionnel Santé - Mainframe",
        "Cobol - Java",
        "Consultant Fonctionnel JD",
        "Concepteur Mainframe",
        "JD Fonctionnel",
        "CP technique JAVA/ELK",
        "Consultante Fonctionnelle (ex souss-traitante QMI)",
        "Support N2 (ex-sous-traitant TITS)",
        "java junior",
        "Ingénieur Systèmes Linux - Chef de projet Infra",
        "Référent Technique",
        "Dieu tout pusisant",
        "BPL (actuellement fonctionnelle SAP)",
        "Expert Technique/architecte/CP Infra",
        "Session JAVA",
        "IE JAVA / Angular",
        "Front",
        "coordination",
        "Session PACBASE",
        "DEV .NET",
        "Java, Selenium, MOA",
        "VMOE, pilotage",
        "Pilotage",
        "Jeune Java",
        ".Net, Java",
        "AF, CP junior",
        "AMOA/PMO",
        "java j2EE junior",
        "ANDROID",
        "Data Analyse / MOA / PMO",
        "Développeur/Lead Developpeur PACBASE",
        "mvs pacbase",
        "CP Java",
        "Chef de projet technico-fonctionnel",
        "Developpeur",
        "Développeuse .NET",
        "Campus OAIO",
        "Développeur Front End",
        "CP Junior",
        "integration/ CP",
        "cp mvs",
        "cp/pmo",
        "Cobol, fonctionnel",
        "ANALYSTE FONCT",
        "IED Junior Mobile",
        "IED C#/.NET",
        "Consultant Fonctionnel/AMOA PLM",
        "Java, C++",
        "BI - reporting - DigDash/BO",
        "DEV Mobile JAVA/Android/iOS (ex-stagiaire)",
        "PO/Chef de projet Fonctionnel",
        "Dev Full Stack",
        "CP MOA/MOE",
        "Java/J2EE",
        "Coach Agile/Scrum Master",
        "Infra SAP",
        "CP / PO / BPL",
        "AMOA Senior",
        "AMOA confirmée",
        "PMO / Pilote de projet",
        "COBOL WINDEV",
        "Dev Mobile/ Angular",
        "IED Junior C,JAVA (ex-stagiaire)",
        "IED  (ex-stagiaire)",
        "DP/CP",
        "Directeur d'hôpital",
        "Professeur de lycée professionnel ou technique",
        "Automaticien Tests",
        "Testeur Fonctionnel",
        "Analyste de Tests",

    ]
    def skill(self):

        return self.random_element(self, skills)


fake.add_provider(Provider)